# Generated by Django 5.1.3 on 2025-05-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticqrcode',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/backgrounds/'),
        ),
        migrations.AlterModelTable(
            name='dynamicqrcode',
            table='application_dynamicqrcode',
        ),
    ]
