# Generated by Django 5.2 on 2025-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_staticqrcode_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticqrcode',
            name='background_image',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/backgrounds/'),
        ),
    ]
