# Generated by Django 5.2 on 2025-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_staticqrcode_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='format',
            field=models.CharField(choices=[('png', 'PNG'), ('svg', 'SVG'), ('jpg', 'JPG'), ('pdf', 'PDF')], default='png', max_length=10),
        ),
        migrations.DeleteModel(
            name='CreatedQrCodes',
        ),
    ]
