# Generated by Django 5.2 on 2025-05-14 02:17

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_qrcode_format_delete_createdqrcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_code',
            field=models.ImageField(upload_to=application.models.QRCode.qr_code_upload_path),
        ),
    ]
