# Generated by Django 5.2 on 2025-05-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='hash_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
